# Data from Table: https://en.wikipedia.org/wiki/List_of_most-followed_Instagram_accounts
# Original Source: https://www.socialtracker.io/toplists/top-50-instagram-users-by-followers/

data = [
    {
        "name": "Instagram",
        "follower_count": 662,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 611,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 492,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 430,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 398,
        "description": "Media personality",
        "country": "United States",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 392,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 381,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 364,
        "description": "Media personality",
        "country": "United States",
    },
    {
        "name": "Beyoncé",
        "follower_count": 318,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Khloé Kardashian",
        "follower_count": 311,
        "description": "Media personality",
        "country": "United States",
    },
    {
        "name": "Nike",
        "follower_count": 306,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "name": "Kendall Jenner",
        "follower_count": 294,
        "description": "Media personality",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 292,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "National Geographic",
        "follower_count": 283,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 275,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Virat Kohli",
        "follower_count": 262,
        "description": "Cricketer",
        "country": "India",
    },
    {
        "name": "Jennifer Lopez",
        "follower_count": 252,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 228,
        "description": "Musician",
        "country": "Trinidad and Tobago",
    },
    {
        "name": "Kourtney Kardashian",
        "follower_count": 224,
        "description": "Media personality",
        "country": "United States",
    },
    {
        "name": "Neymar",
        "follower_count": 216,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 215,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 206,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 185,
        "description": "Actress and singer",
        "country": "United States",
    },
    {
        "name": "Kevin Hart",
        "follower_count": 179,
        "description": "Comedian and actor",
        "country": "United States",
    },
    {
        "name": "Cardi B",
        "follower_count": 169,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "LeBron James",
        "follower_count": 158,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Demi Lovato",
        "follower_count": 157,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Rihanna",
        "follower_count": 152,
        "description": "Musician",
        "country": "Barbados",
    },
    {
        "name": "Real Madrid CF",
        "follower_count": 149,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Chris Brown",
        "follower_count": 144,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Drake",
        "follower_count": 144,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Ellen DeGeneres",
        "follower_count": 139,
        "description": "Comedian and television host",
        "country": "United States",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 124,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "UEFA Champions League",
        "follower_count": 111,
        "description": "Club football competition",
        "country": "Europe",
    },
    {
        "name": "Billie Eilish",
        "follower_count": 110,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Kylian Mbappé",
        "follower_count": 109,
        "description": "Footballer",
        "country": "France",
    },
    {
        "name": "Gal Gadot",
        "follower_count": 109,
        "description": "Actress",
        "country": "Israel",
    },
    {
        "name": "Vin Diesel",
        "follower_count": 101,
        "description": "Actor",
        "country": "United States",
    },
    {
        "name": "Lisa",
        "follower_count": 98.7,
        "description": "Musician",
        "country": "Thailand",
    },
    {
        "name": "NASA",
        "follower_count": 96.8,
        "description": "Space agency",
        "country": "United States",
    },
    {
        "name": "Priyanka Chopra",
        "follower_count": 89.8,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "Shakira",
        "follower_count": 89.7,
        "description": "Musician",
        "country": "Colombia",
    },
    {
        "name": "Dua Lipa",
        "follower_count": 88.7,
        "description": "Musician",
        "country": "United Kingdom",
    },
    {
        "name": "David Beckham",
        "follower_count": 84.9,
        "description": "Former footballer",
        "country": "United Kingdom",
    },
    {
        "name": "Shraddha Kapoor",
        "follower_count": 84.2,
        "description": "Actress",
        "country": "India",
    },
    {
        "name": "NBA",
        "follower_count": 83.7,
        "description": "Professional basketball league",
        "country": "United States",
    },
    {
        "name": "Snoop Dogg",
        "follower_count": 82.3,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Jennie",
        "follower_count": 81.8,
        "description": "Musician",
        "country": "South Korea",
    },
    {
        "name": "Narendra Modi",
        "follower_count": 80.9,
        "description": "Prime Minister of India",
        "country": "India",
    },
    {
        "name": "Khaby Lame",
        "follower_count": 80.8,
        "description": "Media personality",
        "country": "Italy",
    },
]
