# print("Hello World!\nHello World!\nHello World!")
# print("Hello" + " " + "Jordan")
# print("Hello " + input("What is your name? "))
name = input("What is your name? ")
length = len(name)
print(name)
print(length)
